### ISSUE TITLE
Device not found

### ISSUE THREAD

**Issue by 777funk** [stefanocoding/take_control#2]
I've played around with the device id a bit (referring to the other issue) and it still seems to not be found unfortunately. It does show up in the Pulse audio sound device list so it is connected ok.

**Comment by stefanocoding** [comment]
Hi @777funk. Which device are you trying to manage? I wrote the script for the Apogee Duet that is compatible with iOS.

**Comment by 777funk** [comment]
Hi @stefanocoding 

yes this is an Apogee Duet in Linux. The script opens a window but the window says No Duet Found or something to that effect. I messed with the device id in the .py script but no luck.

**Comment by stefanocoding** [comment]
I just tested it on Ubuntu 22.04.2 running on VirtualBox and it worked. 
What do you get when you run `lsusb | grep Apogee`?

**Comment by 777funk** [comment]
> 

This is the original silver Apogee Duet (connects via Firewire). So lsusb shouldn't show anything, no?

**Comment by DerEber** [comment]
Look at the other issue I opened.
I am having the Duett II usb.
Got the code partly working.

**Comment by 777funk** [comment]
> Look at the other issue I opened. I am having the Duett II usb. Got the code partly working.

I did see that and tried your device id. I also tried a few more.

**Comment by stefanocoding** [comment]
> > 
> 
> This is the original silver Apogee Duet (connects via Firewire). So lsusb shouldn't show anything, no?

Oh, that's why it doesn't work. I made it for the USB device, not the Firewire one. Sorry about not specifying that it in the README. I just updated it. 
Did you check out http://www.ffado.org/ ? They may be helpful with your device. Maybe it's already supported.

**Comment by stefanocoding** [comment]
> Look at the other issue I opened. I am having the Duett II usb. Got the code partly working.

I responded to that issue. Without your specific device I'm not able to tune the script to work with your device. I will leave the issue open in case I can figure out how to make it work.
